name: Analyze pull request

# then define on which event, here a push
on:
   pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
      - '[0-9]_[0-9]_x'

# We can now build our job
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SONAR_TOKEN }}
          host: ${{ secrets.SONAR_HOST_URL }}
          projectKey: testing-project
