name: Analyze pull request

# then define on which event, here a push
on:
   push:
    branches: [main]
   pull_request:
    branches: [main]

# We can now build our job
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SONAR_TOKEN }}
          host: ${{ secrets.SONAR_HOST_URL }}
          projectKey: testing-project
