# Start by giving a name to your workflow
name: Analyze branch

# then define on which event, here a push
on:
   push:
    branches: [main]
   pull_request:
    branches: [main]

# We can now build our job
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
       projectBaseDir: app/src
       args: >
        -Dsonar.projectKey=testing-project
